# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-21 18:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegedetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='user_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
