# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collegedetails', '0002_auto_20170921_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(blank=True, max_length=255)),
                ('emailAdress', models.CharField(blank=True, max_length=255)),
                ('projectdetails', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
